// Catálogo Oficial Curado de los 30 Hipódromos Más Populares (Orden Alfabético A-Z)
const CHANNELS = [
  {
    id: "aqueduct-racetrack",
    name: "Aqueduct Racetrack",
    flag: "🇺🇸",
    location: "Queens, New York, EE.UU.",
    type: "iframe",
    aliases: ["aqueduct", "aqueductracetrack"],
    streamUrl: "/offair.html?track=Aqueduct%20Racetrack&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Queens%2C%20New%20York%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Aqueduct%20Racetrack&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Queens%2C%20New%20York%2C%20EE.UU.",
    officialSource: "NYRA Official Live Feed",
    statusText: "Carreras en Vivo • NYRA HD Directo",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "belmont-park",
    name: "Belmont Park",
    flag: "🇺🇸",
    location: "Elmont, New York, EE.UU.",
    type: "iframe",
    aliases: ["belmont", "belmontpark"],
    streamUrl: "/offair.html?track=Belmont%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Elmont%2C%20New%20York%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Belmont%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Elmont%2C%20New%20York%2C%20EE.UU.",
    officialSource: "NYRA Official Live (New York Racing Association)",
    statusText: "Carreras en Vivo • NYRA HD Directo",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "cal-racing",
    name: "Cal Racing",
    flag: "🇺🇸",
    location: "California, EE.UU.",
    type: "iframe",
    aliases: ["cal racing", "calracing"],
    streamUrl: "/offair.html?track=Cal%20Racing&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=California%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Cal%20Racing&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=California%2C%20EE.UU.",
    officialSource: "California Authority Racing Feed",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "capital-otb",
    name: "Capital OTB TV Network",
    flag: "🇺🇸",
    location: "New York, EE.UU.",
    type: "iframe",
    aliases: ["capital otb", "capitalotb"],
    streamUrl: "/offair.html?track=Capital%20OTB%20TV%20Network&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=New%20York%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Capital%20OTB%20TV%20Network&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=New%20York%2C%20EE.UU.",
    officialSource: "Capital OTB Official Feed",
    statusText: "Carreras en Vivo • OTB HD Directo",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "churchill-downs",
    name: "Churchill Downs",
    flag: "🇺🇸",
    location: "Louisville, Kentucky, EE.UU.",
    type: "iframe",
    aliases: ["churchill", "churchilldowns"],
    streamUrl: "/offair.html?track=Churchill%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Louisville%2C%20Kentucky%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Churchill%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Louisville%2C%20Kentucky%2C%20EE.UU.",
    officialSource: "Churchill Downs Official Stream",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "colonial-downs",
    name: "Colonial Downs",
    flag: "🇺🇸",
    location: "New Kent, Virginia, EE.UU.",
    type: "iframe",
    aliases: ["colonial", "colonialdowns"],
    streamUrl: "/offair.html?track=Colonial%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=New%20Kent%2C%20Virginia%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Colonial%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=New%20Kent%2C%20Virginia%2C%20EE.UU.",
    officialSource: "Colonial Downs Official Stream",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "del-mar",
    name: "Del Mar",
    flag: "🇺🇸",
    location: "Del Mar, California, EE.UU.",
    type: "iframe",
    aliases: ["del mar", "delmar"],
    streamUrl: "/offair.html?track=Del%20Mar&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Del%20Mar%2C%20California%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Del%20Mar&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Del%20Mar%2C%20California%2C%20EE.UU.",
    officialSource: "Del Mar Thoroughbred Club Official",
    statusText: "Carreras en Vivo • DMTC HD Directo",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "delaware-park",
    name: "Delaware Park",
    flag: "🇺🇸",
    location: "Wilmington, Delaware, EE.UU.",
    type: "iframe",
    aliases: ["delewar park", "delaware", "delawarepark"],
    streamUrl: "/offair.html?track=Delaware%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Wilmington%2C%20Delaware%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Delaware%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Wilmington%2C%20Delaware%2C%20EE.UU.",
    officialSource: "Delaware Park Official Feed",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "ellis-park",
    name: "Ellis Park",
    flag: "🇺🇸",
    location: "Henderson, Kentucky, EE.UU.",
    type: "iframe",
    aliases: ["ellis", "ellispark"],
    streamUrl: "/offair.html?track=Ellis%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Henderson%2C%20Kentucky%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Ellis%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Henderson%2C%20Kentucky%2C%20EE.UU.",
    officialSource: "Ellis Park Official Stream",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "evangeline-downs",
    name: "Evangeline Downs",
    flag: "🇺🇸",
    location: "Opelousas, Louisiana, EE.UU.",
    type: "iframe",
    aliases: ["evangeline", "evangelinedowns"],
    streamUrl: "/offair.html?track=Evangeline%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Opelousas%2C%20Louisiana%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Evangeline%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Opelousas%2C%20Louisiana%2C%20EE.UU.",
    officialSource: "Evangeline Downs Live Feed",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "finger-lakes",
    name: "Finger Lakes",
    flag: "🇺🇸",
    location: "Farmington, New York, EE.UU.",
    type: "iframe",
    aliases: ["finger", "fingerlakes"],
    streamUrl: "/offair.html?track=Finger%20Lakes&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Farmington%2C%20New%20York%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Finger%20Lakes&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Farmington%2C%20New%20York%2C%20EE.UU.",
    officialSource: "Finger Lakes Gaming & Racetrack Official",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "gulfstream-park",
    name: "Gulfstream Park",
    flag: "🇺🇸",
    location: "Hallandale Beach, Florida, EE.UU.",
    type: "iframe",
    aliases: ["gustripark", "gulstream park", "gustrempark", "gutrimpark", "gulfstream"],
    streamUrl: "/offair.html?track=Gulfstream%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Hallandale%20Beach%2C%20Florida%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Gulfstream%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Hallandale%20Beach%2C%20Florida%2C%20EE.UU.",
    officialSource: "XBTV / Gulfstream Park Live Official",
    statusText: "Carreras en Vivo • XBTV HD Directo",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "hawthorne",
    name: "Hawthorne Race Course",
    flag: "🇺🇸",
    location: "Stickney/Cicero, Illinois, EE.UU.",
    type: "iframe",
    aliases: ["hawthorne"],
    streamUrl: "/offair.html?track=Hawthorne%20Race%20Course&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Stickney%2FCicero%2C%20Illinois%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Hawthorne%20Race%20Course&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Stickney%2FCicero%2C%20Illinois%2C%20EE.UU.",
    officialSource: "Hawthorne Official Stream",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "hipodromo-palermo",
    name: "Hipódromo de Palermo",
    flag: "🇦 repertorio",
    location: "Buenos Aires, Argentina",
    type: "iframe",
    aliases: ["palermo", "hipodromopalermo"],
    streamUrl: "/offair.html?track=Hip%C3%B3dromo%20de%20Palermo&flag=%F0%9F%87%A6%F0%9F%87%B7&loc=Buenos%20Aires%2C%20Argentina",
    iframeUrl: "/offair.html?track=Hip%C3%B3dromo%20de%20Palermo&flag=%F0%9F%87%A6%F0%9F%87%B7&loc=Buenos%20Aires%2C%20Argentina",
    officialSource: "Hipódromo de Palermo Oficial",
    statusText: "Carreras en Vivo • Palermo HD Directo",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "horseshoe-indianapolis",
    name: "Horseshoe Indianapolis",
    flag: "🇺🇸",
    location: "Shelbyville, Indiana, EE.UU.",
    type: "iframe",
    aliases: ["indianapolis", "indiana", "horseshoe"],
    streamUrl: "/offair.html?track=Horseshoe%20Indianapolis&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Shelbyville%2C%20Indiana%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Horseshoe%20Indianapolis&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Shelbyville%2C%20Indiana%2C%20EE.UU.",
    officialSource: "Horseshoe Indiana Official Live Feed",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "keeneland",
    name: "Keeneland",
    flag: "🇺🇸",
    location: "Lexington, Kentucky, EE.UU.",
    type: "iframe",
    aliases: ["keeneland"],
    streamUrl: "/offair.html?track=Keeneland&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Lexington%2C%20Kentucky%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Keeneland&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Lexington%2C%20Kentucky%2C%20EE.UU.",
    officialSource: "Keeneland Official Stream",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "kentucky-downs",
    name: "Kentucky Downs",
    flag: "🇺🇸",
    location: "Franklin, Kentucky, EE.UU.",
    type: "iframe",
    aliases: ["kentucky downs", "kentuckydowns"],
    streamUrl: "/offair.html?track=Kentucky%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Franklin%2C%20Kentucky%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Kentucky%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Franklin%2C%20Kentucky%2C%20EE.UU.",
    officialSource: "Kentucky Downs Official Stream",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "la-rinconada",
    name: "La Rinconada",
    flag: "🇻🇪",
    location: "Caracas, Venezuela",
    type: "iframe",
    aliases: ["rinconada", "inh", "larinconada"],
    streamUrl: "https://www.youtube.com/embed/live_stream?channel=UC_INH_OFICIAL",
    iframeUrl: "https://www.youtube.com/embed/live_stream?channel=UC_INH_OFICIAL",
    officialSource: "INH Oficial (Instituto Nacional de Hipódromos)",
    statusText: "Carreras en Vivo • INH Oficial HD Directo",
    nextRace: "Jornada Dominical en Vivo"
  },
  {
    id: "laurel-park",
    name: "Laurel Park",
    flag: "🇺🇸",
    location: "Laurel, Maryland, EE.UU.",
    type: "iframe",
    aliases: ["laurepar", "laurel"],
    streamUrl: "/offair.html?track=Laurel%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Laurel%2C%20Maryland%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Laurel%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Laurel%2C%20Maryland%2C%20EE.UU.",
    officialSource: "Maryland Racing Live Official",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "los-alamitos",
    name: "Los Alamitos",
    flag: "🇺🇸",
    location: "Cypress, California, EE.UU.",
    type: "iframe",
    aliases: ["los alamitos", "losalamitos"],
    streamUrl: "/offair.html?track=Los%20Alamitos&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Cypress%2C%20California%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Los%20Alamitos&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Cypress%2C%20California%2C%20EE.UU.",
    officialSource: "Los Alamitos Official Feed",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "monmouth-park",
    name: "Monmouth Park",
    flag: "🇺🇸",
    location: "Oceanport, New Jersey, EE.UU.",
    type: "iframe",
    aliases: ["moumouth park", "momon parker", "monmouth"],
    streamUrl: "/offair.html?track=Monmouth%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Oceanport%2C%20New%20Jersey%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Monmouth%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Oceanport%2C%20New%20Jersey%2C%20EE.UU.",
    officialSource: "Monmouth Park Live Official Feed",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "mountaineer-park",
    name: "Mountaineer Park",
    flag: "🇺🇸",
    location: "New Cumberland, West Virginia, EE.UU.",
    type: "iframe",
    aliases: ["mountaineer", "mountaineerpark"],
    streamUrl: "/offair.html?track=Mountaineer%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=New%20Cumberland%2C%20West%20Virginia%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Mountaineer%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=New%20Cumberland%2C%20West%20Virginia%2C%20EE.UU.",
    officialSource: "Mountaineer Official Stream",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "parx-racing",
    name: "Parx Racing",
    flag: "🇺🇸",
    location: "Bensalem, Pennsylvania, EE.UU.",
    type: "iframe",
    aliases: ["parx", "parxracing"],
    streamUrl: "/offair.html?track=Parx%20Racing&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Bensalem%2C%20Pennsylvania%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Parx%20Racing&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Bensalem%2C%20Pennsylvania%2C%20EE.UU.",
    officialSource: "Parx Racing Live Feed",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "presque-isle",
    name: "Presque Isle Downs",
    flag: "🇺🇸",
    location: "Erie, Pennsylvania, EE.UU.",
    type: "iframe",
    aliases: ["presque isle", "presqueisle"],
    streamUrl: "/offair.html?track=Presque%20Isle%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Erie%2C%20Pennsylvania%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Presque%20Isle%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Erie%2C%20Pennsylvania%2C%20EE.UU.",
    officialSource: "Presque Isle Official Feed",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "santa-anita-park",
    name: "Santa Anita Park",
    flag: "🇺🇸",
    location: "Arcadia, California, EE.UU.",
    type: "iframe",
    aliases: ["santa anita", "santaanita"],
    streamUrl: "/offair.html?track=Santa%20Anita%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Arcadia%2C%20California%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Santa%20Anita%20Park&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Arcadia%2C%20California%2C%20EE.UU.",
    officialSource: "Santa Anita Park Official Live Stream",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "saratoga",
    name: "Saratoga",
    flag: "🇺🇸",
    location: "Saratoga Springs, New York, EE.UU.",
    type: "iframe",
    aliases: ["saratoga", "nyra saratoga"],
    streamUrl: "/offair.html?track=Saratoga&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Saratoga%20Springs%2C%20New%20York%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Saratoga&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Saratoga%20Springs%2C%20New%20York%2C%20EE.UU.",
    officialSource: "NYRA Official Live (New York Racing Association)",
    statusText: "Carreras en Vivo • NYRA HD Directo",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "tampa-bay-downs",
    name: "Tampa Bay Downs",
    flag: "🇺🇸",
    location: "Tampa, Florida, EE.UU.",
    type: "iframe",
    aliases: ["tampa bay", "tampabay"],
    streamUrl: "/offair.html?track=Tampa%20Bay%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Tampa%2C%20Florida%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Tampa%20Bay%20Downs&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Tampa%2C%20Florida%2C%20EE.UU.",
    officialSource: "Tampa Bay Downs Official Feed",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "thistledown",
    name: "Thistledown",
    flag: "🇺🇸",
    location: "North Randall, Ohio, EE.UU.",
    type: "iframe",
    aliases: ["tristledawons", "thistledow", "thistledown"],
    streamUrl: "/offair.html?track=Thistledown&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=North%20Randall%2C%20Ohio%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=Thistledown&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=North%20Randall%2C%20Ohio%2C%20EE.UU.",
    officialSource: "Thistledown Gaming & Racing Official Feed",
    statusText: "Carreras en Vivo • Feed Oficial HD",
    nextRace: "Siguiente Carrera en Vivo"
  },
  {
    id: "vsin",
    name: "VSiN Sports Network",
    flag: "🇺🇸",
    location: "Las Vegas, Nevada, EE.UU.",
    type: "iframe",
    aliases: ["vsin", "vsin sports"],
    streamUrl: "/offair.html?track=VSiN%20Sports%20Network&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Las%20Vegas%2C%20Nevada%2C%20EE.UU.",
    iframeUrl: "/offair.html?track=VSiN%20Sports%20Network&flag=%F0%9F%87%BA%F0%9F%87%B8&loc=Las%20Vegas%2C%20Nevada%2C%20EE.UU.",
    officialSource: "VSiN Live Sports Network",
    statusText: "Transmisión en Vivo • VSiN HD Directo",
    nextRace: "En Directo"
  },
  {
    id: "woodbine",
    name: "Woodbine",
    flag: "🇨🇦",
    location: "Toronto, Ontario, Canadá",
    type: "iframe",
    aliases: ["woobine", "woodbine"],
    streamUrl: "/offair.html?track=Woodbine&flag=%F0%9F%87%A8%F0%9F%87%A6&loc=Toronto%2C%20Ontario%2C%20Canad%C3%A1",
    iframeUrl: "/offair.html?track=Woodbine&flag=%F0%9F%87%A8%F0%9F%87%A6&loc=Toronto%2C%20Ontario%2C%20Canad%C3%A1",
    officialSource: "Woodbine Racetrack Official Live Feed",
    statusText: "Carreras en Vivo • Woodbine Official HD",
    nextRace: "Siguiente Carrera en Vivo"
  }
];

module.exports = CHANNELS;
